FROM golang:latest as build

COPY . src
RUN cd src &&  CGO_ENABLED=0 GOOS=linux GOPATH=$(path) go build -o /azmount github.com/Microsoft/confidential-sidecar-containers/cmd/azmount
RUN cd src &&  CGO_ENABLED=0 GOOS=linux GOPATH=$(path) go build -o /remotefs github.com/Microsoft/confidential-sidecar-containers/cmd/remotefs
RUN cd src/tools/get-snp-report && make && mv bin/get-snp-report / && mv bin/get-fake-snp-report /

FROM alpine:3.17.1

RUN apk update && apk --no-cache add cryptsetup fuse curl

RUN mkdir -p bin

COPY --from=build /azmount ./bin/
COPY --from=build /remotefs ./bin/
COPY --from=build /get-snp-report ./bin/
COPY docker/encfs/encfs.sh /
RUN chmod +x /*.sh && date > /made-date

# set the start command
CMD [ "sleep", "1000000" ]
