apiVersion: v1
kind: Pod
metadata:
 name: aasp-secret-provisioning
spec:
  runtimeClassName: kata
  containers:
  - image: $AASP_IMAGE
    imagePullPolicy: Always
    name: aasp
    command: [/bin/aasp]
    env:
    - name: CertCacheEndpoint
      value: "ewogICAgImNlcnRjYWNoZSI6IHsKCQkiZW5kcG9pbnRfdHlwZSI6ICJBekNhY2hlIiwKCQkiZW5kcG9pbnQiOiAiYW1lcmljYXMudGVzdC5hY2NjYWNoZS5henVyZS5uZXQiLAoJCSJ0ZWVfdHlwZSI6ICJTZXZTbnBWTSIsCgkJImFwaV92ZXJzaW9uIjogImFwaS12ZXJzaW9uPTIwMjAtMTAtMTUtcHJldmlldyIKCX0gIAp9"
    volumeMounts:
    - mountPath: /dev/sev
      name: dev-sev
    - mountPath: /common
      name: common
    securityContext:
      privileged: true
  - image: $SAMPLE_UNWRAP_IMAGE
    imagePullPolicy: Always
    name: sample-unwrap
    command: ["/bin/sh","-c"]
    args: ["sleep infinity"]
    volumeMounts:
    - mountPath: /common
      name: common
  imagePullSecrets:
    - name: $ACR_SECRET
  volumes:
  - name: dev-sev
    hostPath:
      path: /dev/sev
  - name: common
    emptyDir: {}