name: Push Encrypted FS Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_encfs_image.yml
      - cmd/azmount/**
      - cmd/remotefs/**
      - docker/encfs/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_encfs_image.yml
      - cmd/azmount/**
      - cmd/remotefs/**
      - docker/encfs/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
    
      
jobs:

  push-encfs-image: 
    name: Push Encrypted FS Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Image
        run: docker/encfs/build.sh
        
      - name: Push Image
        run: docker/encfs/push.sh ${{ secrets.REGISTRY_NAME }} ${{ secrets.REGISTRY_DOMAIN }} encfs:${{ github.ref }}