name: Push SKR Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      
jobs:

  push-skr-image: 
    name: Push SKR Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: Build Image
        run: docker/skr/build.sh
        
      - name: Push Image
        run: docker/skr/push.sh ${{ secrets.REGISTRY_NAME }} ${{ secrets.REGISTRY_DOMAIN }} skr:${{ github.ref }}