name: Push SKR Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      
jobs:

  push-skr-image: 
    name: Push SKR Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Log in to Azure Container Registry
        run: |
          az acr login \ 
            --name ${{ secrets.REGISTRY_NAME }} \
            --username ${{ secrets.REGISTRY_NAME }} \
            --password ${{ secrets.REGISTRY_PASSWORD }} 
          
      - name: Get Branch Name
        id: get_branch_name
        run: |
          if [ ${{ github.event_name }} == "pull_request" ]; then
            echo "branch_name=$(echo ${{ github.head_ref }})" >> $GITHUB_OUTPUT
          else
            echo "branch_name=$(echo ${{ github.ref }})" >> $GITHUB_OUTPUT
          fi
        
      - name: Build Image
        run: docker/skr/build.sh
        
      - name: Push Image
        run: |
          docker/skr/push.sh \
            ${{ secrets.REGISTRY_NAME }} \
            ${{ secrets.REGISTRY_DOMAIN }} \
            skr:${{ steps.get_branch_name.outputs.branch_name }}
