name: Push Encrypted FS Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_encfs_image.yml
      - cmd/azmount/**
      - cmd/remotefs/**
      - docker/encfs/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_encfs_image.yml
      - cmd/azmount/**
      - cmd/remotefs/**
      - docker/encfs/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report

jobs:
  push-encfs-image:
    name: Push Encrypted FS Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Log in to Azure Container Registry
        run: |
          az acr login \
            --name ${{ secrets.REGISTRY_NAME }} \
            --username ${{ secrets.REGISTRY_NAME }} \
            --password ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Image
        run: docker/encfs/build.sh

      - name: Push Image
        run: |
          if [ ${{ github.event_name }} == "push" ]; then
            branch_name=main
          else  
            branch_name=$(echo ${{ github.head_ref }})
          fi
          docker/encfs/push.sh \
            ${{ secrets.REGISTRY_NAME }} \
            ${{ secrets.REGISTRY_DOMAIN }} \
            encfs:$branch_name \
            --skip-login
