name: Push SKR Debug Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_debug_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      - tools/get-snp-report/bin/verbose-report
      
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_debug_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      - tools/get-snp-report/bin/verbose-report
      
jobs:

  push-skr-debug-image: 
    name: Push SKR Debug Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Get Branch Name
        id: get_branch_name
        run: |
          if [ ${{ github.event_name }} == "pull_request" ]; then
            echo "branch_name=$(echo ${{ github.head_ref }})" >> $GITHUB_OUTPUT
          else
            echo "branch_name=$(echo ${{ github.ref }})" >> $GITHUB_OUTPUT
          fi
        
      - name: Build Image
        run: docker/skr/build-debug.sh
        
      - name: Push Image
        uses: docker/build-push-action@v3
        with:
          file: docker/skr/Dockerfile.debug
          push: true
          tags: |
            ${{ secrets.REGISTRY_NAME }}.${{ secrets.REGISTRY_DOMAIN }}/skr_debug:${{ stesp.get_branch_name.outputs.branch_name }}
        