name: Push SKR Debug Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_debug_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      - tools/get-snp-report/bin/verbose-report
      
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_skr_debug_image.yml
      - cmd/skr/**
      - docker/skr/**
      - tools/get-snp-report/bin/get-snp-report
      - tools/get-snp-report/bin/get-fake-snp-report
      - tools/get-snp-report/bin/verbose-report
      
jobs:

  push-skr-debug-image: 
    name: Push SKR Debug Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Image
        run: docker/skr/build-debug.sh
        
      - name: Push Image
        run: docker/skr/push.sh ${{ secrets.REGISTRY_NAME }} ${{ secrets.REGISTRY_DOMAIN }} skr_debug:${{ github.ref }}